version: '2.3'

volumes:
  db: ~

services:
  web:
    image: nginx:1.15.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/src/app
      - ./docker/config/ssl:/etc/nginx/ssl
      - ./docker/config/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - "app"
    networks:
      - code-network

  app:
    image: node:8.15-stretch
    ports:
      - "3003:3003"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    depends_on:
      - "db"
    networks:
      - code-network

  db:
    image: mysql:5.7
    ports:
      - "33061:3306"
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
